version: 2
updates:
  - package-ecosystem: 'docker'
    directory: '/docker'
    open-pull-requests-limit: 20
    schedule:
      interval: 'monthly'
    registries:
      - ghcr
    labels:
      - dependencies
      - docker
      - Fanout
    groups:
      dependabot-core-images:
        patterns:
          - dependabot/*
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - dependencies
      - github_actions
      - Fanout      
  - package-ecosystem: 'npm'
    directory: '/'
    open-pull-requests-limit: 20
    schedule:
      interval: 'monthly'
    labels:
      - dependencies
      - javascript
      - Fanout      

registries:
  ghcr:
    type: docker-registry
    url: ghcr.io
    username: x
    password: ${{ secrets.DEPENDABOT_GHPR_TOKEN }}
